version: "2"

services:

  test-client:
    depends_on:
      - test-server
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-client
    working_dir: /work
    volumes:
      - ..:/work
  test-server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-server
    working_dir: /work
    expose:
      - "9999"
    volumes:
      - ..:/work

